### ISSUE TITLE
Installaton error and import component

### ISSUE THREAD

**Issue by jhderojasUVa** [rdkcentral/Lightning-UI-Components#11]
I found two errors on documentation and an small failure:

**Installation error**

npm command doesn't work because it's not registered on the standard npm directory.

**Solution**

You can add that dependency by editing the package.json file and addiding on the _devDependencies_ section/property:

`"lightning-ui-components": "git+https://github.com/rdkcentral/Lightning-UI-Components.git"`

On that way you are adding it directly from the git.

Of course you can do the same on the _npm i_ command, but I don't remember the syntax (sorry, blame me).

**Component importation error**

Using the way that is included on the components to import them doesn't work.

**Solution**

After installing at the way above, the correct way to import a component is (Column example, but for the others is the same).

```js
import Column from 'lightning-ui-components/components/Column/index'
```

This is because there's no index that export all the components on the `/components/` directory and at the _package.json_ file there's no `main` property to tell the package where to find the main entry of the components.

**Comment by chiefcll** [comment]
👋 

Thanks for the issue and the heads up. We'll be updating this repo next week with a lot of changes and will address this bug then.

**Comment by chiefcll** [comment]
We've updated the index file so this should work now. Let us know if you have an issue, we're also working on releasing on NPM - stay tuned
