### ISSUE TITLE
Feature request: Infinite scrolling style of wrapping

### ISSUE THREAD

**Issue by edatencio-velope** [rdkcentral/Lightning-UI-Components#18]
Hello!

Currently, the wrapping style of the row component is scrolling back to the first item. It would be very nice if you could add a wrapping style that makes the row appear infinite. It doesn't need to duplicate items because we are using enough to fill the screen width.

**Comment by chiefcll** [comment]
We almost have this PR ready... Hopefully early next week

**Comment by vmend** [comment]
@chiefcll Hello, any news on this? Thank you!
