### ISSUE TITLE
Bug: Column component consumes input events when it shouldn't

### ISSUE THREAD

**Issue by edatencio-velope** [rdkcentral/Lightning-UI-Components#19]
Hello!

If you select the column component's first element and press the Up button, it consumes the input event. The expected behavior is for it to ignore the event because it's already on the first element. Because of this, I can't navigate from the column to the component above it.

This issue began when the `update-row` branch was merged into master a couple of days ago. I have not verified if the row has the same problem.

**Comment by chiefcll** [comment]
I'll be looking into this later today
