### ISSUE TITLE
Bug: Column items shouldn't display outside of the column area

### ISSUE THREAD

**Issue by edatencio-velope** [rdkcentral/Lightning-UI-Components#21]
Hello,

I updated our project to the latest version of this repo and noticed the column items are being rendered outside its area.

If I move the column near the bottom edge of the screen, the items before the current index overlap with other components instead of hiding away.

This bug is not present on commit `0e0c303`. I have not verified if the row has the same problem.

**Comment by vmend** [comment]
![image (2) (2)](https://user-images.githubusercontent.com/62772382/109648224-492aab80-7b52-11eb-9791-9f5d8a533703.png)

**Comment by chiefcll** [comment]
Can you set `clip: true` on the column component - that should hide overflow

**Comment by edatencio-velope** [comment]
> Can you set `clip: true` on the column component - that should hide overflow

I tried your solution, but it didn't work 😕

**Comment by edatencio-velope** [comment]
That does the trick, thank you! 😁
