### ISSUE TITLE
Issue with Row component after the latest update

### ISSUE THREAD

**Issue by MykhailoDz** [rdkcentral/Lightning-UI-Components#33]
Hello guys! After the latest update when I use Column + Rows components for building the Grid component I faced this issue : 
![image](https://user-images.githubusercontent.com/46669878/118513955-cec6fc00-b73c-11eb-9cf9-21535f079d09.png)
Here is how it look like before the update : 
![image](https://user-images.githubusercontent.com/46669878/118514111-f4540580-b73c-11eb-8874-6faa4350966f.png)
Also, after debugging lightning-ui-components package I see that on Row component we patch **this.Items** with **nextH**: 
![image](https://user-images.githubusercontent.com/46669878/118514428-367d4700-b73d-11eb-8821-9be1ed207c32.png)
(previously you patched nextH  directly to Row component :   `this.patch( {h: nextH }` ). If we add this code to Row component then everythning works as expected : 
![image](https://user-images.githubusercontent.com/46669878/118514953-97a51a80-b73d-11eb-8258-8d499afb8723.png)

Please review this issue and will be great to see the fix in the next version!
Thank you,

**Comment by chiefcll** [comment]
@MykhailoDz - I think this was a bug with the previous row component - we've moved away from the Row getting its height from its children as some items could be varying height.

Can you set the Row height when you create the row and see if that fixes it.
