### ISSUE TITLE
Issue with Column component after update relase1.0

### ISSUE THREAD

**Issue by ZhipengJuly** [rdkcentral/Lightning-UI-Components#34]
Hello guys, after i update the release1.0 version, i found the Column can't be scrolled. I debuged found that caused by the render(next, prev)function, ‘this.itemsChangeable’ is awalys true, so the 'this._performRender()' won't be called.
![image](https://user-images.githubusercontent.com/18577053/118576723-a7fbda80-b7bb-11eb-8a54-cd724be2afce.png)
I found the 'this.itemsChangeable' set to true in the '$itemChanged()' and not changed anymore. 
![image](https://user-images.githubusercontent.com/18577053/118576934-0fb22580-b7bc-11eb-92c3-5fccb91ea228.png)
Is that a bug, please help, thanks.

**Comment by erautenberg** [comment]
@ZhipengJuly thank you for your feedback and I apologize for the long delay. We are currently working to overhaul this repo, so a new version of the Column should be available in the next week or so that addresses this exact concern.

**Comment by anthony9187** [comment]
Hi @ZhipengJuly, the latest release (v1.1.0) resolves this issue. I'll close this now, but let us know if you continue having any problems. Thanks for all of your feedback!
