### ISSUE TITLE
How to improve performance when there are many data items?

### ISSUE THREAD

**Issue by CooperCao** [rdkcentral/Lightning-UI-Components#43]
Hi Guys,
When I use Column, if there are many data items, the switching will be very slow. Is there any way to improve performance?

**Comment by chiefcll** [comment]
Hi - I recommend doing a performance recording and seeing what is happening when you're switching. The column component just does the initial layout of the components and sets up _handleKeys to switch between data items. The switching just changes the getFocused and shouldn't cause any performance issues. You'll need to look at what is happening when an element is focused / unfocused to see if you're doing too much on the main thread.
