### ISSUE TITLE
Bug Found: Keyboard component is not exported. 

### ISSUE THREAD

**Issue by jay-patel9** [rdkcentral/Lightning-UI-Components#50]
Location - Lightning-UI-Components/index.js

In index.js Keyboard component and KEYBOARD_FORMATS are not exported. So, the import is not possible when using the library.

**Comment by erautenberg** [comment]
@jay-patel9  thank you for your feedback! We are currently working to overhaul this repo, so a new version of the Keyboard (and our exports_ should be available in the coming weeks that addresses this issue.

**Comment by anthony9187** [comment]
Hi @jay-patel9, this issue is resolved in the latest release(v1.1.0). I'm going to close this, but if you continue to have problems with the Keyboard please reach out to us again. Thanks!
