### ISSUE TITLE
Published package missing "Styles" and "textures" directories

### ISSUE THREAD

**Issue by justinmenking** [rdkcentral/Lightning-UI-Components#87]
The `@lightningjs/ui-components` package is currently un-usable, as the Styles and textures folders are missing, but the index file attempts to export components from them.

This can be verified by:
* Install version 1.2.0 with npm in a newly initialized project.
* Open `node_modules/@lightningjs/ui-components`
* Observe Styles and textures folders are missing
* Observe that index.js is importing from those folders.

**Comment by THoj13** [comment]
Hi @justinmenking, thanks for calling this out. A fix for this is in review (https://github.com/rdkcentral/Lightning-UI-Components/pull/86) and should be resolved in the next release.

**Comment by anthony9187** [comment]
Hi @justinmenking, the latest release ([v1.2.1](https://github.com/rdkcentral/Lightning-UI-Components/releases/tag/v1.2.1)) contains a fix for this bug. Thanks for reporting this!

**Comment by justinmenking** [comment]
Thanks for the quick fix, looks good to me.
